### ISSUE TITLE
getUserDeviceType() in helpers mobility doesn't work

### ISSUE THREAD

**Issue by arunjoseph** [Logiks/Logiks-Core#11]
The function getUserDeviceType() from api/helpers/mobility.php#L11-L28 is not functional
Following is the test snippet used to test.

```php
public function test_getUserDeviceType() {
	$tz = getUserDeviceType();
	$expected = 'PC';
	$this->assertEquals($expected,$tz);
}
```

**Comment by Logiks** [comment]
This test case failed because console does not support user-agents or any similar facility for detecting user device. We tested the code in real time scenarios and the functionality works.
