### ISSUE TITLE
getRelativePath() is not functional

### ISSUE THREAD

**Issue by arunjoseph** [Logiks/Logiks-Core#16]
The getRelativePath() function from **api/helpers/pathfuncs.php#L13-L21** does not return anything yet, in the following screenshot there is no output from the test case even though using the following test case suggested by you.

```php
$tz=getRelativePath("/srcspace/wwwLogiks/devlogiks/media/images/bug.png");
$expected='../../../';
$this->assertEquals($expected,$tz);//comes true
```
![screenshot from 2015-11-24 11 09 14](https://cloud.githubusercontent.com/assets/1634000/11358795/f4dc2b52-929b-11e5-9cab-2ca79679612b.png)
```

**Comment by Logiks** [comment]
Fixed in latest iteration.
