### ISSUE TITLE
formatDateToMySQL() is not functional

### ISSUE THREAD

**Issue by arunjoseph** [Logiks/Logiks-Core#18]
formatDateToMySQL() from the helper **api/helpers/dateops.php#L162-L166** is failing the functionality test for the given test case

```php
$date1 = '05/10/1992';
$actual = formatDateToMySQL($date1);
$expected = '1992-10-05';
$this->assertEquals($expected,$actual);
```

**Comment by Logiks** [comment]
This function is not longer included in Logiks latest iterations.
