### ISSUE TITLE
Template Inheritance

### ISSUE THREAD

**Issue by Logiks** [Logiks/Logiks-Core#3]
Template inheritance should be there or at least templates should allow embedding other templates within them, this would save a lot of copy paste between similar themes.

**Comment by bismay4u** [comment]
Resolved in Logiks 4.0. New template engine not only solves the inheritance and other minor objectives, but also brings together many great features like
- Tighter Logiks Integration , now you can use components, contents, widgets, modules right from inside the templates.
- Multiple Template Engine includes Smarty. Blade and twig to be introduced really soon. Only one engine can be used per app.
-Better and cleaner integration.
