### ISSUE TITLE
getRelativePath() is not functional

### ISSUE THREAD

**Issue by arunjoseph** [Logiks/Logiks-Core#9]
The getRelativePath() function from **api/helpers/pathfuncs.php#L13-L21** does not return anything rather it gives a blank testcase result. Following is the code used to test the correctness of the function
``` php
$tz=getRelativePath('/');
echo $path;
$expected='/var/www';
$this->assertEquals($expected,$tz);
```

**Comment by Logiks** [comment]
The above test case is wrong. getRelativePath() returns the number of jumps the current file is from the Root directory

```
$tz=getRelativePath("/srcspace/wwwLogiks/devlogiks/media/images/bug.png");
$expected='../../../';
$this->assertEquals($expected,$tz);//comes true
```

**Comment by arunjoseph** [comment]
In the following screenshot there is no output from the test case even though using the 

```php
$tz=getRelativePath("/srcspace/wwwLogiks/devlogiks/media/images/bug.png");
$expected='../../../';
$this->assertEquals($expected,$tz);//comes true
```
![screenshot from 2015-11-24 11 09 14](https://cloud.githubusercontent.com/assets/1634000/11358795/f4dc2b52-929b-11e5-9cab-2ca79679612b.png)
